version: '3.8'
services:
  flask-app:
    image: trefle-gang-flask
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    command: flask run --host=0.0.0.0 --reload
    volumes:
      - .:/app