name: Continuous development

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: trefle-gang
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker image tag
        id: setup_tag
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            echo "::set-output name=tag::$(echo ${GITHUB_REF#refs/heads/})"
          elif [ "${{ github.event_name }}" == "release" ]; then
            echo "::set-output name=tag::${{ github.event.release.tag_name }}"
          fi

      - name: Build Docker image
        run: docker build . -t helbiii/treflegang:${{ steps.setup_tag.outputs.tag }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.USER_DOCK_HUB }}
          password: ${{ secrets.PASS_DOCK_HUB }}

      - name: Push Docker image
        run: docker push helbiii/treflegang:${{ steps.setup_tag.outputs.tag }}

    if: github.event_name == 'push' || (github.event_name == 'release' && github.event.action == 'published')
