name: CI/CD Workflow

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'
  release:
    types: [published]

jobs:

  build-and-push:
    runs-on: ubuntu-latest
    environment: trefle-gang
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build . -t my-flask-app:${{ github.sha }}
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.USER_DOCK_HUB }}
          password: ${{ secrets.PASS_DOCK_HUB }}
      - name: Push Docker image
        run: docker push my-flask-app:${{ github.sha }}
    if: github.event_name == 'push' || (github.event_name == 'release' && github.event.action == 'published')
